# Generated by Django 6.1 on 2026-08-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_order_orderitem_orderstatushistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice_sent",
            field=models.BooleanField(default=False),
        ),
    ]
