# Generated by Django 6.1 on 2026-08-09 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_order_invoice_sent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_number", models.CharField(max_length=50, unique=True)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("RETURN", "Return"),
                            ("EXCHANGE", "Exchange"),
                            ("REPLACEMENT", "Replacement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("requested_quantity", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PICKUP_SCHEDULED", "Pickup Scheduled"),
                            ("PICKED_UP", "Picked Up"),
                            ("RECEIVED", "Received"),
                            ("INSPECTING", "Inspecting"),
                            ("EXCHANGE_PROCESSING", "Exchange Processing"),
                            ("REPLACEMENT_PROCESSING", "Replacement Processing"),
                            ("REFUND_PROCESSING", "Refund Processing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="REQUESTED",
                        max_length=30,
                    ),
                ),
                (
                    "requested_exchange_size",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "requested_exchange_color",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("admin_notes", models.TextField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_requests",
                        to="core.order",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_requests",
                        to="core.orderitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReturnRequestImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="returns/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.returnrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReturnRequestStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PICKUP_SCHEDULED", "Pickup Scheduled"),
                            ("PICKED_UP", "Picked Up"),
                            ("RECEIVED", "Received"),
                            ("INSPECTING", "Inspecting"),
                            ("EXCHANGE_PROCESSING", "Exchange Processing"),
                            ("REPLACEMENT_PROCESSING", "Replacement Processing"),
                            ("REFUND_PROCESSING", "Refund Processing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=30,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="core.returnrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
