# Generated by Django 6.1 on 2026-08-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_category_collection_adminauditlog_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="primary_image_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
