# Generated by Django 6.0.7 on 2026-08-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_product_primary_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store_name",
                    models.CharField(default="URBN Clothing", max_length=255),
                ),
                (
                    "store_email",
                    models.EmailField(default="vp05112007@gmail.com", max_length=254),
                ),
                ("low_stock_threshold", models.PositiveIntegerField(default=5)),
                ("return_window_days", models.PositiveIntegerField(default=7)),
                (
                    "shipping_charge",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("store_currency", models.CharField(default="INR", max_length=10)),
                ("order_prefix", models.CharField(default="URBN", max_length=10)),
            ],
        ),
    ]
