# Generated by Django 6.1 on 2026-08-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_storesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
